linters:
  enable:
    - nakedret 
    - interfacer
    - varcheck
    - deadcode 
    - structcheck 
    - misspell
    - maligned 
    - ineffassign
    - goconst
    - goimports
    - errcheck 
    - dupl 
    - unparam 
    - golint 
    - staticcheck
    - unused
    - gosimple
run:
linters-settings:
  errcheck:
    check-type-assertions: true
